### PR TITLE
Update weapon skills and duplicate starting items

### LINKED ISSUE #19: Missing weapon skills
Hi, if you start as a dwarf druid you only get the staves as a weapons skill. You do not get the dagger/mace as a night elf does. I didn't check other race/class combos.

The reference here https://www.azerothcore.org/wiki/playercreateinfo_spell_custom says you should enable "PlayerStart.AllSpells" which doesn't exist, but instead in worldserver.conf I enabled this:

PlayerStart.CustomSpells = 1

As it sound like that should be needed, since the included SQL has a lot of changes for table playercreateinfo_spell_custom.

But no luck, it's not working for me. If the above "PlayerStart.CustomSpells = 1" had fixed it, I would just have made a PR with an update to the README.md file.

I'm currently on mod-arac 2e7040352385f4cff9a9fce77cf562d65b689a19 and azerothcore 0df153b8ddaa8b28002462ce955c509b9fe04aed (less than 48 hours old).

### PR DESCRIPTION
**Pull request by shuddertrix**
SkillRaceClassInfo.dbc has been modified to allow all races access to all weapon skills. The weapon skills are still limited by the ClassMask field, allowing only the correct classes to learn weapon skills. The SkillRaceClassInfo.dbc file has been added to Patch-A.MPQ as the client needs this DBC file to allow unlearned weapon skills to be learned at weapon trainers. Fixes #19

AzerothCore does not need items added in the playercreateinfo_item table - it parses CharStartOutfit.dbc for items to add. Fixes comments mentioned in #16 where duplicate items would be added to a character's inventory upon creation.

### CODE REVIEW

**Comment by heyitsbench** [comment]
I'm very sorry I did not see this sooner. I will do some basic tests either tonight or tomorrow and hopefully nothing bad will show itself. Thank you very much for the PR!

**Comment by MatthewHinds** [comment]
> I'm very sorry I did not see this sooner. I will do some basic tests either tonight or tomorrow and hopefully nothing bad will show itself. Thank you very much for the PR!

Hey just wanted to check if you've had any luck on this? Hope all is well

**Comment by shuddertrix** [comment]
> > I'm very sorry I did not see this sooner. I will do some basic tests either tonight or tomorrow and hopefully nothing bad will show itself. Thank you very much for the PR!
> 
> Hey just wanted to check if you've had any luck on this? Hope all is well

We've been running the updated version for several weeks on our private server (a project currently in word-of-mouth open beta) and there have been no more reports of incorrect weapon skills. I hope Bench finds the same in his tests!

**Comment by heyitsbench** [comment]
> Hey just wanted to check if you've had any luck on this? Hope all is well

Thank you for the reminder! I found no outstanding issues with this PR, so it's good to merge.

> We've been running the updated version for several weeks on our private server (a project currently in word-of-mouth open beta) and there have been no more reports of incorrect weapon skills. I hope Bench finds the same in his tests!

Thank you for your own testing, and thank you very much for the PR! I'm sure you're already well aware, but this PR brings a huge improvement to the usability of this module. ❤️

**Pull request merged**
